---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
  - name: routing-release-ci
  - name: networking-oss-deployments

run:
  path: routing-release-ci/ci/tasks/bosh2-command/task

params:
  NUMBER_OF_RUNS:
  ENVIRONMENT:
  DEPLOYMENT:
  COMMAND:
