---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: routing-release-ci
  - name: toolsmiths-metadata-dir
  - name: networking-oss-deployments

outputs:
  - name: drats-integration-config

params:
  ENVIRONMENT:

run:
  path: routing-release-ci/ci/tasks/create-drats-config-toolsmiths/task
