---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
- name: bbl-state
- name: routing-release-ci
- name: plan-patches

outputs:
- name: updated-bbl-state

params:
  BBL_STATE_DIR:  # relative to env-repo input
  PLAN_PATCH_DIR:  # relative to plan-patches input
  GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
  GIT_COMMIT_USERNAME: CI Bot
  GIT_COMMIT_MSG: Adding plan patches

run:
  path: routing-release-ci/ci/tasks/inject-plan-patches/task
